model_list:
- model_name: openrouter/*
  litellm_params:
    model: openrouter/*
    api_key: os.environ/OPENROUTER_API_KEY

general_settings:
  user_header_name: x-openwebui-user-name 
  master_key: os.environ/LITELLM_MASTER_KEY
  health_check_interval: 300
  detailed_debug: true
litellm_settings:
  check_provider_endpoint: true
  drop_params: true
  set_verbose: false
  request_timeout: 600
  success_callback:
  - langfuse
  failure_callback:
  - langfuse
