model_list:
  # OpenRouter models - popular and capable models
  - model_name: gpt-4o
    litellm_params:
      model: openrouter/openai/gpt-4o
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      
  - model_name: gpt-4o-mini
    litellm_params:
      model: openrouter/openai/gpt-4o-mini
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      
  - model_name: claude-3-haiku
    litellm_params:
      model: openrouter/anthropic/claude-3-haiku
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1

# General settings for simple gateway mode
general_settings:
  # Parse user info from OpenWebUI headers
  user_header_name: X-OpenWebUI-User-Id
  
  # No database required for simple gateway
  database_url: null
  
  # Master key for admin access (optional)
  master_key: os.environ/LITELLM_MASTER_KEY
  
  # Enable health checks
  health_check_interval: 300

# LiteLLM proxy settings
litellm_settings:
  # Drop unsupported parameters
  drop_params: true
  
  # Basic logging
  set_verbose: false
  
  # Request timeout
  request_timeout: 600