model_list:
- model_name: openai-gpt-oss-120b
  litellm_params:
    model: openrouter/openai/gpt-oss-120b
    api_key: os.environ/OPENROUTER_API_KEY
    api_base: https://openrouter.ai/api/v1
    max_tokens: 32768

general_settings:
  user_header_name: x-openwebui-user-name 
  master_key: os.environ/LITELLM_MASTER_KEY
  health_check_interval: 300
  detailed_debug: true
  disable_prisma_schema_update: true
  custom_auth: false
litellm_settings:
  drop_params: true
  set_verbose: false
  request_timeout: 600
  success_callback:
  - class_callback.FileLogger
  failure_callback:
  - class_callback.FileLogger
