services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "${LITELLM_PORT:-4000}:4000"
    networks:
      - llmnet
    volumes:
      - ./startup.sh:/app/startup.sh:ro
      - ./custom_langfuse_callback.py:/app/custom_langfuse_callback.py:ro
      - ./simple_callback.py:/app/simple_callback.py:ro
      - ./config.yaml:/app/config.yaml:ro
    env_file:
      - ./litellm.env
    entrypoint: ["/bin/bash", "/app/startup.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:4000/health/liveliness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  llmnet:
    external: true