services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "${LITELLM_PORT:-4000}:4000"
    networks:
      - llmnet
    volumes:
      - ./update-models.py:/app/update-models.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./startup.sh:/app/startup.sh:ro
      - ./config.yaml.j2:/app/config.yaml.j2:ro
      - ./custom_callbacks.py:/app/custom_callbacks.py:ro
      - ./custom_langfuse_callback.py:/app/custom_langfuse_callback.py:ro
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-sk-1234}
      - LITELLM_SALT_KEY=${LITELLM_SALT_KEY}
      - CONFIG_PATH=/app/config.yaml
      - LITELLM_VERBOSE=${LITELLM_VERBOSE:-false}
      - LITELLM_REQUEST_TIMEOUT=${LITELLM_REQUEST_TIMEOUT:-600}
      - LITELLM_ENABLE_CACHING=${LITELLM_ENABLE_CACHING:-false}
      - LITELLM_ENABLE_FALLBACKS=${LITELLM_ENABLE_FALLBACKS:-false}
      - UI_USERNAME=${UI_USERNAME:-admin}
      - UI_PASSWORD=${UI_PASSWORD:-changeme}
      - DISABLE_ADMIN_UI=${DISABLE_ADMIN_UI:-false}
      - PROXY_BASE_URL=${PROXY_BASE_URL:-http://localhost:4000}
      # Langfuse configuration
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST:-https://langfuse.brandonbryant.io}
      - LANGFUSE_DEBUG=true
      - LITELLM_LOG=DEBUG
    entrypoint: ["/bin/bash", "/app/startup.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:4000/health/liveliness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  llmnet:
    external: true