model_list:
  - model_name: qwen3-32b
    litellm_params:
      model: openai/qwen3-32b
      api_base: http://localhost:3000/v1
      api_key: sk-local
    
  - model_name: qwen3-14b
    litellm_params:
      model: openai/qwen3-14b
      api_base: http://localhost:3000/v1
      api_key: sk-local

  - model_name: qwen3-8b
    litellm_params:
      model: openai/qwen3-8b
      api_base: http://localhost:3000/v1
      api_key: sk-local

  - model_name: qwen3-4b
    litellm_params:
      model: openai/qwen3-4b
      api_base: http://localhost:3000/v1
      api_key: sk-local