version: '3.8'

services:
  db:
    image: postgres:16
    container_name: litellm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: litellm
      POSTGRES_DB: litellm
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # LiteLLM proxy service
  litellm:
    image: litellm/litellm:latest
    platform: linux/amd64
    container_name: litellm-proxy
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml:ro
      - ui_data:/app/ui                                   # persist Web UI
    environment:
      - DATABASE_URL=postgresql://litellm:litellm@db:5432/litellm
    entrypoint: ["/bin/sh", "-c"]                       # run shell first
    command: |
      litellm --config /app/config.yaml --port 4000 --host 0.0.0.0
    restart: unless-stopped

volumes:
  db_data:
    driver: local
  ui_data:                                                # volume for downloaded UI
    driver: local