version: '3.8'

services:
  # LiteLLM proxy service
  litellm:
    image: litellm/litellm:latest
    platform: linux/amd64
    container_name: litellm-proxy
    ports:
      - "${LITELLM_PORT:-4000}:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml:ro
      - ui_data:/app/ui                                   # persist Web UI
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
    entrypoint: ["/bin/sh", "-c"]                       # run shell first
    command: |
      litellm --config /app/config.yaml --port 4000 --host 0.0.0.0 --detailed_debug
    restart: unless-stopped

volumes:
  ui_data:                                                # volume for downloaded UI
    driver: local