services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    # OpenWebUI listens on 8080 in-container; expose on configurable host port
    ports:
      - "${OPENWEBUI_PORT:-3000}:8080"
    networks:
      - llmnet
    volumes:
      # persists chats, users, settings
      - open-webui:/app/backend/data
    environment:
      # Disable signups for production
      - ENABLE_SIGNUP=false
      # Forward user info as headers to downstream APIs
      - ENABLE_FORWARD_USER_INFO_HEADERS=true
    restart: unless-stopped

networks:
  llmnet:
    external: true

volumes:
  open-webui: