model_list:
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
      max_tokens: 4096
      temperature: 0.7

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  
  langfuse:
    public_key: os.environ/LANGFUSE_PUBLIC_KEY
    secret_key: os.environ/LANGFUSE_SECRET_KEY
    host: os.environ/LANGFUSE_HOST
    
  drop_params: false
  set_verbose: false
  
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: null
  max_parallel_requests: 100
  infer_model_from_keys: false