model_list:
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
      max_tokens: 4096
      temperature: 0.7

litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  
  # Langfuse configuration
  langfuse:
    public_key: os.environ/LANGFUSE_PUBLIC_KEY
    secret_key: os.environ/LANGFUSE_SECRET_KEY
    host: os.environ/LANGFUSE_HOST
  
  # Forward all OpenWebUI user headers as metadata tags for rich tracking
  extra_spend_tag_headers:
    - "X-OpenWebUI-User-Name"
    - "X-OpenWebUI-User-Id" 
    - "X-OpenWebUI-User-Role"
    - "X-OpenWebUI-User-Email"
    - "X-OpenWebUI-Session-Id"
    - "X-OpenWebUI-Chat-Id"
    - "X-OpenWebUI-Model"
    - "X-OpenWebUI-Title"
    
  drop_params: false
  set_verbose: true  # Enable verbose logging to see all headers
  
general_settings:
  # Primary user identifier for Langfuse (can be User-Id, User-Email, or User-Name)
  user_header_name: X-OpenWebUI-User-Email
  
  # Optional: Also capture user ID as secondary identifier
  user_api_key_alias: X-OpenWebUI-User-Id
  
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: null
  max_parallel_requests: 100
  infer_model_from_keys: false
  
  # Enable detailed request/response logging
  detailed_debug: true